name: Hand Whittled
favicon: null
layout_spectrum: 0.5025
typography_spectrum: 0.46172
title: hand whittled
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#484848'
    - '#c0c0c0'
    - '#0d0d0d'
    - '#e35435'
  brandStrength: 1
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
