name: Hand Whittled
favicon: null
layout_spectrum: 0
typography_spectrum: 0.46172
title: hand whittled
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9e4fa2'
    - '#000000'
    - '#f09403'
    - '#ff00ff'
    - '#ffffff'
  brandStrength: 0.043517990969121456
  lightness: 0
  saturation: 0
  rhythmicContrast: 0.18425473989918828
purpose: []
